# Generated by Django 5.2.3 on 2025-06-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('wearables', 'Wearables'), ('accessories', 'Accessories'), ('audio', 'Audio'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
